'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Feren_OS_DE_preview.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____100_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____100_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____125_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____125_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____130_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____130_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____133_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____133_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____173_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____173_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____197_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____197_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____2_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____2_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____23_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____23_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____28_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____28_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____30_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____30_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____32_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____32_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____33_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____33_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____39_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____39_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____39_IV_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____39_IV_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____42_III_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____42_III_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____47_III_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____47_III_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____55_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____55_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____63_III_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____63_III_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____67_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____67_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____68_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____68_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____81_III_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____81_III_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____86_III_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____86_III_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____90_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____90_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____94_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____94_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____96_II_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____96_II_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____96_II_1920_1200_with_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____96_II_1920_1200 with logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _____96_III_1920_1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____96_III_1920_1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1440x900() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1440x900", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9_Beta__231_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9 Beta (231)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9_Beta__236_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9 Beta (236)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Apparence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Apparence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Apps_button_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Apps_button_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Audio_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Audio_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Audio_Icon_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Audio_Icon 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Audio_Icon_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Audio_Icon 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Audio_Icon_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Audio_Icon 4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Autumn_Season() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Autumn Season", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BackTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battery_Icon___Charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Icon + Charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battery_Icon_1_High() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Icon 1 High", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battery_Icon_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Icon 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battery_Icon_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Icon 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battery_Icon_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Icon 4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battery_Icon_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Icon 5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battery_Icon_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Icon 6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Battery_Icon_7_Low() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Battery_Icon 7 Low", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Busy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Busy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calendrier_avec_Date() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendrier_avec_Date", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CloseDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CloseDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CloseNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CloseNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Computer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Computer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Défender() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Défender", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Download_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang4105\deflangfe4105\themelang4105\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        '''{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 00000000000000000000}Cambria Math;}{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property editHelpFile() As String
            Get
                Return ResourceManager.GetString("editHelpFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Explorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property File_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("File_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Film_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Film_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fond_d_écran_d_ouverture_de_session() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fond d'écran d'ouverture de session", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FormSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home_1_Month_Activate_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home(1-Month Activate)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home_desk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home desk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kittenfox_Internet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kittenfox Internet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lake_frost_by_zaz369_d6yek84() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lake_frost_by_zaz369-d6yek84", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lake_frost_by_zaz369_d6yek84_with_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lake_frost_by_zaz369-d6yek84 with logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lake_frost_by_zaz369_d6yek84_with_logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lake_frost_by_zaz369-d6yek84 with logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login 4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login 5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login 6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login 7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login 8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logoicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logoicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logoiconselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logoiconselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MaximizeNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaximizeNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinimizeDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinimizeDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MinimizeNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MinimizeNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property More() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("More", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Movies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Movies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MultiDesk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MultiDesk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Musique_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Musique_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Neige() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Neige", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Normal() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NotePad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotePad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang4105{\fonttbl{\f0\froman\fcharset0 Times New Roman;}{\f1\fnil\fcharset0 Calibri;}}
        '''{\colortbl ;\red0\green77\blue187;}
        '''{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sb100\sa100\cf1\f0\fs24 What is Note?\cf0\par
        '''Note is a basic text-editing program and it&apos;s most commonly used to view or edit text files. A text file is a file type typically identified by the .txt file name extension.\par
        '''\pard\sa200\sl276\slmult1\cf1\lang9\f1\fs22 --------------------------- [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ntpdHelpFile() As String
            Get
                Return ResourceManager.GetString("ntpdHelpFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nuageux() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nuageux", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Orageux() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Orageux", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Parametre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Parametre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Perspective() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perspective", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Petite_icone_démarrage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Petite_icone_démarrage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Photo_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Photo_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pluie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pluie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang2057\deflangfe2057\themelang2057\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        '''{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}T [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property printingHelpFile() As String
            Get
                Return ResourceManager.GetString("printingHelpFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Redbgnew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Redbgnew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RestoreNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RestoreNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shield_Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shield_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shield_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin1Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin1Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin2Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin2Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skin3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sleepy_kitten_by_amelka_wonka_kitty_d3ecixm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sleepy_kitten_by_amelka_wonka_kitty-d3ecixm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Soleil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Soleil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Soleil___Nuages() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Soleil___Nuages", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spring_Season() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spring Season", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Store() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Store", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Summer_days() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Summer days", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Summer_Season() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Summer Season", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Switch_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Switch off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Switch_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Switch on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Taskbar_logo_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Taskbar logo new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Terminal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terminal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Touch_UI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Touch UI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Touch_UI_checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Touch UI checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Triangular() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Triangular", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_10__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 10 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_11__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 11 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_2__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 2 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_3__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 3 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_4__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 4 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_5__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 5 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_6__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 6 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_7__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 7 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_8__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 8 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_9__Carré_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User 9 (Carré)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Vista_SystemExit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Vista_SystemExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Vista_SystemStart() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Vista_SystemStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property whitemusicsmallnewnewnewnew_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("whitemusicsmallnewnewnewnew!", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property WIB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WIB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wifi_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wifi-Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wifi_Icon_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wifi-Icon 5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property windows_7_reimagined_wallpaper_by_gifteddeviant_d566kgg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows_7_reimagined_wallpaper_by_gifteddeviant-d566kgg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property windows_vista_loading____by_luthien_surion_d31802o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows_vista_loading____by_luthien_surion-d31802o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Winter_Season() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Winter Season", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Within() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Within", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ZOS_Desk_White() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZOS Desk White", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ZOS_Desk_White_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZOS Desk White new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zuaro_OS_Default_Desktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zuaro OS Default Desktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zuaro_OS_Default_Desktop_checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zuaro OS Default Desktop checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zuaro_OS_desk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zuaro OS desk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zuaro_OS_deskshade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zuaro OS deskshade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
